### ISSUE TITLE
Route Guard

### ISSUE THREAD

**Issue by dprastha** [fradotech/fullstack-laravel-onboarding#1]
Apakah bisa ditambahkan route guard?

Ref: https://laravel.com/docs/10.x/middleware#assigning-middleware-to-routes

**Comment by fradotech** [comment]
Syudahh mas

Code:
<img width="583" alt="image" src="https://github.com/fradotech/fullstack-laravel-onboarding/assets/55073493/4b28df49-e656-42da-ace2-17a7088a84cd">

Unautorized
<img width="1440" alt="image" src="https://github.com/fradotech/fullstack-laravel-onboarding/assets/55073493/80d4f79c-25de-4bd2-8202-2a2130bb7fc5">

**Comment by dprastha** [comment]
LGTM
