### ISSUE TITLE
Route Model Binding

### ISSUE THREAD

**Issue by dprastha** [fradotech/fullstack-laravel-onboarding#2]
Untuk mendapatkan data route seperti edit user bisa menggunakan Route Model Binding agar tidak perlu melakukan query manual.

Ref: https://laravel.com/docs/10.x/routing#route-model-binding

Source code yang direview:
<img width="430" alt="image" src="https://github.com/fradotech/fullstack-laravel-onboarding/assets/57651747/ab5235e7-0f75-40ec-81ba-037c7637176b">

**Comment by fradotech** [comment]
Bisa otomatiss gokill wkwkk

Code:
<img width="535" alt="image" src="https://github.com/fradotech/fullstack-laravel-onboarding/assets/55073493/2e78d6e3-446b-4f4e-9167-91aacc072759">

Example:
<img width="739" alt="image" src="https://github.com/fradotech/fullstack-laravel-onboarding/assets/55073493/8e438ca7-8085-41e2-848d-5d42246336e8">

**Comment by dprastha** [comment]
Laravel is magic, LGTM
