### ISSUE TITLE
Show error message each form input

### ISSUE THREAD

**Issue by dprastha** [fradotech/fullstack-laravel-onboarding#3]
Menampilkan pesan error di masing-masing form input.

Ref: https://inertiajs.com/forms

**Comment by fradotech** [comment]
Eh ku kira gak sampai ke FE nyaa mas kemarinn wkwkk

Code:
<img width="463" alt="image" src="https://github.com/fradotech/fullstack-laravel-onboarding/assets/55073493/2a19d078-4f43-49b0-8959-1439c0c37b32">

Example:
<img width="1270" alt="image" src="https://github.com/fradotech/fullstack-laravel-onboarding/assets/55073493/6167ecf7-c53d-4fec-a29b-df4ef1aede28">

**Comment by dprastha** [comment]
Biar sekalian wkwkkw, LGTM
