### ISSUE TITLE
Custom error message validation

### ISSUE THREAD

**Issue by dprastha** [fradotech/fullstack-laravel-onboarding#4]
Custom pesan error validasi sesuai kebutuhan

Ref: https://laravel.com/docs/10.x/validation#customizing-the-error-messages

**Comment by fradotech** [comment]
Syudahh

Code:
<img width="676" alt="image" src="https://github.com/fradotech/fullstack-laravel-onboarding/assets/55073493/0936baf9-6254-4ff4-a564-f26c00eedd81">

Example:
<img width="1164" alt="image" src="https://github.com/fradotech/fullstack-laravel-onboarding/assets/55073493/2d582755-0611-4a3d-b7f4-d89f5be55022">

**Comment by dprastha** [comment]
LGTM
