### ISSUE TITLE
Create Custom Helper Function

### ISSUE THREAD

**Issue by dprastha** [fradotech/fullstack-laravel-onboarding#5]
Belum ada implementasi custom helper function.

Ref: https://laravel-news.com/creating-helpers

**Comment by fradotech** [comment]
Syudahh

Code:
<img width="1426" alt="image" src="https://github.com/fradotech/fullstack-laravel-onboarding/assets/55073493/b04ca426-4483-447b-9344-f20f24d8a878">

Example:
<img width="952" alt="image" src="https://github.com/fradotech/fullstack-laravel-onboarding/assets/55073493/bf077024-b1fc-42b2-a1ab-f8403d5f9a64">

**Comment by dprastha** [comment]
LGTM
