### ISSUE TITLE
Implement Pagination

### ISSUE THREAD

**Issue by dprastha** [fradotech/fullstack-laravel-onboarding#6]
Coba implementasi pagination di list page

Ref: https://laravel.com/docs/10.x/eloquent-resources#pagination

**Comment by fradotech** [comment]
Syudahh

Code:
<img width="502" alt="image" src="https://github.com/fradotech/fullstack-laravel-onboarding/assets/55073493/484cb3f5-f5ef-4bba-80f2-f8d3d94b0767">

Example:
<img width="878" alt="image" src="https://github.com/fradotech/fullstack-laravel-onboarding/assets/55073493/0978d412-3009-4f5a-9be8-4ff99eedcf75">

**Comment by dprastha** [comment]
LGTM
