### ISSUE TITLE
Request Params Not Satisfied Form Request

### ISSUE THREAD

**Issue by dprastha** [fradotech/fullstack-laravel-onboarding#7]
Di layer service belum menggunakan Form Request. Masih menggunakan Request bawaan/default.

Code yg direview:
<img width="520" alt="image" src="https://github.com/fradotech/fullstack-laravel-onboarding/assets/57651747/7b9c8c91-740d-465e-b869-83616b6ec003">

**Comment by fradotech** [comment]
Oiyaa meskipun tidak ada type trnyata bisa dipakai dingg wkwkk, syudahh mas
<img width="627" alt="image" src="https://github.com/fradotech/fullstack-laravel-onboarding/assets/55073493/c22f0ba2-41c2-4239-aaa9-ab24eda7b950">

**Comment by dprastha** [comment]
typenya bablas, LGTM
