### ISSUE TITLE
New Feature - File Upload

### ISSUE THREAD

**Issue by dprastha** [fradotech/fullstack-laravel-onboarding#8]
Implementasikan File Upload

Ref: https://laravel.com/docs/10.x/filesystem#file-uploads

**Comment by fradotech** [comment]
Syudahh mas

Code:
<img width="631" alt="image" src="https://github.com/fradotech/fullstack-laravel-onboarding/assets/55073493/d0a4f378-e9b1-4a27-af61-d0660c093954">

Example:
<img width="1344" alt="image" src="https://github.com/fradotech/fullstack-laravel-onboarding/assets/55073493/db702bb5-0b17-43f6-8e6d-a5aa4b75630b">

<img width="1414" alt="image" src="https://github.com/fradotech/fullstack-laravel-onboarding/assets/55073493/9302661a-60c0-4e28-80b2-89051fcd9207">

**Comment by dprastha** [comment]
LGTM
